version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "15:00"
      timezone: "Europe/Madrid"
    assignees: ["gonzalopozo"]
    commit-message:
      prefix: "chore: updated production dependencies"
    prefix-development: "chore: updated development dependencies"
    pull-request-branch-name:
      separator: "-"
    groups:
      production:
        patterns: ["express", "cors", "i18next*"]
        dependency-type: production
        update-types: ["minor", "patch"]
      dev-dependencies:
        patterns: ["*"]
        exclude-patterns: ["express", "cors", "i18next*"]
        dependency-type: development
